<a href="https://colab.research.google.com/github/naveenkumark1/Extensive_Vision_and_AI_V.4/blob/master/Week3/pytorch101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
## Pytorch 101
# Pytorch is a machine leanring frame work that helps to build models for research prototyping and also for deployment

## Pytorch - Dataframes
#### In pytorch we have a data frame called Tensor - It is the generalisation of matrix and arrays to a higher dimension.

#### Tensor is an entity with defined order or rank 

#### Scalar - 0 order tensor
#### Vector - 1 order tensor 
#### Matrix - 2 order tensor
#### Array  - 3 order tensor


In [0]:
## Tensor Basics 
## Import Libraries 

import numpy as np
import torch

In [4]:
torch.zeros(0)  ## 0 order with zeros 

tensor([])

In [5]:
torch.zeros(1,2)  ## 1 Order 

tensor([[0., 0.]])

In [6]:
torch.zeros(2,2) ## 2 order 

tensor([[0., 0.],
        [0., 0.]])

In [7]:
# Random 3 order tensor

torch.rand(2,3,4)

tensor([[[0.3523, 0.9218, 0.1918, 0.9380],
         [0.8410, 0.5980, 0.6830, 0.5706],
         [0.3154, 0.1423, 0.7740, 0.7576]],

        [[0.4849, 0.8963, 0.5533, 0.4669],
         [0.9545, 0.2502, 0.9523, 0.2727],
         [0.5511, 0.9631, 0.8850, 0.3691]]])

In [8]:
torch.rand(3,2,3,2)

tensor([[[[0.9167, 0.5336],
          [0.8654, 0.5296],
          [0.3798, 0.6306]],

         [[0.8270, 0.3907],
          [0.2438, 0.3745],
          [0.1670, 0.0022]]],


        [[[0.6252, 0.6777],
          [0.9375, 0.7269],
          [0.2901, 0.9617]],

         [[0.2618, 0.3880],
          [0.8785, 0.4648],
          [0.5538, 0.8861]]],


        [[[0.1382, 0.4022],
          [0.3193, 0.4735],
          [0.0756, 0.1121]],

         [[0.7718, 0.6694],
          [0.3097, 0.9497],
          [0.9585, 0.1762]]]])

REF : https://pytorch.org/docs/stable/torch.html#creation-ops

##Question 1:
How many dimensions are there in a tensor defined as below?

In [9]:
torch.rand(1, 1, 1, 1)

tensor([[[[0.5069]]]])

### Ans 1 - 4 Dimension


In [10]:
torch.rand(2, 3, 4, 5)

tensor([[[[0.6790, 0.6155, 0.0981, 0.6873, 0.6075],
          [0.9692, 0.1978, 0.8722, 0.7857, 0.2266],
          [0.7262, 0.8703, 0.6577, 0.2178, 0.0262],
          [0.4358, 0.2246, 0.0825, 0.4315, 0.8975]],

         [[0.4174, 0.4959, 0.5369, 0.6815, 0.9321],
          [0.8480, 0.2337, 0.0811, 0.1394, 0.3500],
          [0.6354, 0.0675, 0.0869, 0.9355, 0.4289],
          [0.8710, 0.7926, 0.3503, 0.4054, 0.1716]],

         [[0.8333, 0.8216, 0.5195, 0.4585, 0.5875],
          [0.1361, 0.5966, 0.0881, 0.2313, 0.3563],
          [0.7905, 0.0583, 0.3094, 0.8118, 0.9451],
          [0.2166, 0.0765, 0.0724, 0.8326, 0.4128]]],


        [[[0.2597, 0.2206, 0.1479, 0.0730, 0.7287],
          [0.4958, 0.4799, 0.2800, 0.9723, 0.1521],
          [0.4741, 0.2123, 0.5629, 0.1068, 0.0213],
          [0.9222, 0.9997, 0.8870, 0.7693, 0.7045]],

         [[0.8382, 0.3851, 0.8841, 0.3335, 0.6569],
          [0.8154, 0.3600, 0.6941, 0.2791, 0.1100],
          [0.9824, 0.9391, 0.7681, 0.0353, 0.6592],
  

In [11]:
torch.rand(2, 3, 4, 5).size()

torch.Size([2, 3, 4, 5])

In [12]:
torch.rand(2, 3, 4, 5).shape

torch.Size([2, 3, 4, 5])

In [13]:
torch.rand(1, 1, 1, 1).size()

torch.Size([1, 1, 1, 1])

## Python / NumPy / Pytorch interoperability
You can create tensors from python as well as numpy arrays. You can also convert torch tensors to numpy arrays. So, the interoperability between torch and numpy is pretty good.

In [14]:
# Simple Python List
python_list = [1, 2]

# Create a numpy array from python list
numpy_array = np.array(python_list)

# Create a torch Tensor from python list
tensor_from_list = torch.tensor(python_list)

# Create a torch Tensor from Numpy array
tensor_from_array = torch.tensor(numpy_array)                                   ### No Memory copy

# Another way to create a torch Tensor from Numpy array (share same storage)
tensor_from_array_v2 = torch.from_numpy(numpy_array)                            ### Memory Copy

# Convert torch tensor to numpy array
array_from_tensor = tensor_from_array.numpy()

print('List:   ', python_list)
print('Array:  ', numpy_array)
print('Tensor: ', tensor_from_list)
print('Tensor: ', tensor_from_array)
print('Tensor: ', tensor_from_array_v2)
print('Array:  ', array_from_tensor)

List:    [1, 2]
Array:   [1 2]
Tensor:  tensor([1, 2])
Tensor:  tensor([1, 2])
Tensor:  tensor([1, 2])
Array:   [1 2]


Difference between `torch.Tensor` and `torch.from_numpy`

Pytorch aims to be an effective library for computations. What does it mean? It means that pytorch avoids memory copying if it can.

In [15]:
numpy_array[0] = 10

print('Array:  ', numpy_array)
print('Tensor: ', tensor_from_array)
print('Tensor: ', tensor_from_array_v2)

Array:   [10  2]
Tensor:  tensor([1, 2])
Tensor:  tensor([10,  2])


## Question 2:

Assume that we moved our complete (cats vs dogs) image dataset to numpy arrays. Then we use torch.from_numpy to convert these images to tensor. Then we apply a specific data augmentation strategy called "CutOut" which blocks a portion of the image directly on these tensors. What will happen to the accuracy of a model trained on this strategy compared to the one without this strategy? CutOut strategy is shown below:

![alt text](https://)

CutOut

In [16]:
print(tensor_from_array_v2)
tensor_from_array_v2[0]=tensor_from_array_v2[0]+1 ## Assume this is cut out
tensor_from_array_v2

tensor([10,  2])


tensor([11,  2])

### Ans 2 : The accuracy will reduce

##Question 3:

Why do you think we are observing this behavior?

We have two different ways to create tensor from its NumPy counterpart - one copies memory and another one shares the same underlying storage. It works in the opposite way:

In [17]:
array_from_tensor = tensor_from_array.numpy()
print('Tensor: ', tensor_from_array)
print('Array: ', array_from_tensor)

tensor_from_array[0] = 11
print('Tensor: ', tensor_from_array)
print('Array: ', array_from_tensor)

Tensor:  tensor([1, 2])
Array:  [1 2]
Tensor:  tensor([11,  2])
Array:  [11  2]


## Data types

The basic data type of all Deep Learning-related operations is float, but sometimes you may need something else. Pytorch support different number types for its tensors the same way NumPy does it - by specifying the data type on tensor creation or via casting. Ths full list of supported data types can be found here.

https://pytorch.org/docs/stable/tensors.html

In [18]:
tensor = torch.zeros(2, 2)
print('Tensor with default type: ', tensor)
tensor = torch.zeros(2, 2, dtype=torch.float16)
print('Tensor with 16-bit float: ', tensor)
tensor = torch.zeros(2, 2, dtype=torch.int16)
print('Tensor with integers: ', tensor)
tensor = torch.zeros(2, 2, dtype=torch.bool)
print('Tensor with boolean data: ', tensor)

Tensor with default type:  tensor([[0., 0.],
        [0., 0.]])
Tensor with 16-bit float:  tensor([[0., 0.],
        [0., 0.]], dtype=torch.float16)
Tensor with integers:  tensor([[0, 0],
        [0, 0]], dtype=torch.int16)
Tensor with boolean data:  tensor([[False, False],
        [False, False]])


## Question 4:
We saw above that some times numpy and tensors share same storage and changing one changes the other. If we define a rank-2-tensor with ones (dtype of f16), and then convert it into a numpy data type using tensor.numpy() and store it in a variable called "num", and then we perform this operation num = num * 0.5, will the original tensor have 1.0s or 0.5s as its element values?

In [19]:
tensor = torch.ones(2,2, dtype = torch.float16)
num = tensor.numpy()
print(num)
num = num*0.5
print(num)
print(tensor)

[[1. 1.]
 [1. 1.]]
[[0.5 0.5]
 [0.5 0.5]]
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


### Ans 4 : The original tensor will have 1.0 as values

## Question 5:
If the operation `num = num*5` is changed to `num[:] = num*5` will the original tensor have 1.0s or 0.5s as its element values?

In [20]:
tensor = torch.ones(2,2, dtype = torch.float16)
num = tensor.numpy()
print(num)
num[:]=num*0.5
num

[[1. 1.]
 [1. 1.]]


array([[0.5, 0.5],
       [0.5, 0.5]], dtype=float16)

#### Ans 5 : The tensor will have 0.5 as values


# Indexing

Tensor provides access to its elements via the same `[]` operation as a regular python list or NumPy array. However, as you may recall from NumPy usage, the full power of math libraries is accessible only via vectorized operations, i.e. operations without explicit looping over all vector elements in python and using implicit optimized loops in C/C++/CUDA/Fortran/etc. available via special function calls. Pytorch employs the same paradigm and provides a wide range of vectorized operations. Let's take a look at some examples.

Joining a list of tensors together with `torch.cat`

In [21]:
a = torch.zeros(3, 2)
b = torch.ones(3, 2)
print(torch.cat((a, b), dim=0))   #Join row wise - Axis 0

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [22]:
a = torch.zeros(3, 2)
b = torch.ones(3, 2)
print(torch.cat((a, b), dim=1))   #Join column wise - Axis = 1

tensor([[0., 0., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 1., 1.]])


## Question 6:

Is the transpose of concatenated a & b tensor on dimension 1, same as the contatenated tensor of a & b on dimension 0?

In [23]:
a = torch.zeros(3, 2)
b = torch.ones(3, 2)

print(torch.flatten(torch.t(torch.cat((a, b), dim=0))))
print(torch.flatten(torch.t(torch.cat((a, b), dim=1))))

torch.flatten(torch.t(torch.cat((a, b), dim=0)))==torch.flatten(torch.t(torch.cat((a, b), dim=1)))


tensor([0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])


tensor([ True,  True,  True, False, False, False, False, False, False,  True,
         True,  True])

#### Ans 6 : Not the same

#### Indexing with another tensor/array:

In [24]:
a = torch.arange(start=0, end=10)
indices = np.arange(0, 10) > 5
print(a)

print("---------------------")
print(indices)
print(a[indices])

indices = torch.arange(start=0, end=10) %5
print("---------------------")
print(indices)
print(a[indices])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
---------------------
[False False False False False False  True  True  True  True]
tensor([6, 7, 8, 9])
---------------------
tensor([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])
tensor([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])


## Question 7:

`a` is defined as `torch.arange(start=0, end=10)`. We will create` b` using the two operations as below. In both cases do we get the same value?

 

1.   Indices variable created by the modulo operation on arange between 0 and 10. Then a new varialble `b` is created from `a` using the last 5 elements of indices.
2.   Indices variable created by the modulo operation on arange betwenn 1 and 11. Then a new varialble `b` is created from `a` using the last 5 elements of indices.

In [26]:
a = torch.arange(start=0,end=10)
print(a)

indices = torch.arange(start=0, end=10) % 5
print(indices)

b = a[-5:]
print(b)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])


In [27]:
a = torch.arange(start=1,end=11)
print(a)

indices = torch.arange(start=0, end=10) % 5
print(indices)

b = a[-5:]
print(b)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])
tensor([ 6,  7,  8,  9, 10])


### Ans 7 : Both of them are not same

##### What should we do if we have, say, rank-2-tensor and want to select only some rows?

In [36]:
# Create a list of tensor to select the specific rows

tensor = torch.rand((5, 3))
rows = torch.tensor([0, 2])
rows = torch.tensor([0, 2,3,3,4])

print(tensor)
print('-------------')
print(rows)
tensor[rows]

tensor([[0.2284, 0.3343, 0.4620],
        [0.8049, 0.4012, 0.6728],
        [0.7397, 0.6555, 0.0157],
        [0.9685, 0.5289, 0.1113],
        [0.9099, 0.3716, 0.7550]])
-------------
tensor([0, 2, 3, 3, 4])


tensor([[0.2284, 0.3343, 0.4620],
        [0.7397, 0.6555, 0.0157],
        [0.9685, 0.5289, 0.1113],
        [0.9685, 0.5289, 0.1113],
        [0.9099, 0.3716, 0.7550]])

## Question 8:
Consider a tensor defined as `torch.rand((6, 5))`. Is the shape of the new tensor created by taking the 0th, 2nd and 4th row of the old tensor same as the shape of the a newer tensor created by taking the 0th, 2nd and 4th row of the old tensor after transposing it by operation `torch.transpose(tensor, 0, 1)` ?

In [42]:
tensor = torch.rand((6,5))
print(tensor)
rows = torch.tensor([0,2,4])
print("###########")
print(tensor[rows])
print("------------------------")
tensor2 = torch.transpose(tensor,0,1)
print(tensor2)
rows = torch.tensor([0,2,4])
print("###########")
print(tensor2[rows])

tensor([[0.1445, 0.4261, 0.5070, 0.9529, 0.5919],
        [0.6191, 0.8271, 0.0301, 0.6545, 0.6822],
        [0.8177, 0.3696, 0.2572, 0.6758, 0.6130],
        [0.8839, 0.3676, 0.8463, 0.7124, 0.7989],
        [0.0373, 0.5876, 0.3284, 0.2814, 0.7659],
        [0.0040, 0.0492, 0.6825, 0.6807, 0.3362]])
###########
tensor([[0.1445, 0.4261, 0.5070, 0.9529, 0.5919],
        [0.8177, 0.3696, 0.2572, 0.6758, 0.6130],
        [0.0373, 0.5876, 0.3284, 0.2814, 0.7659]])
------------------------
tensor([[0.1445, 0.6191, 0.8177, 0.8839, 0.0373, 0.0040],
        [0.4261, 0.8271, 0.3696, 0.3676, 0.5876, 0.0492],
        [0.5070, 0.0301, 0.2572, 0.8463, 0.3284, 0.6825],
        [0.9529, 0.6545, 0.6758, 0.7124, 0.2814, 0.6807],
        [0.5919, 0.6822, 0.6130, 0.7989, 0.7659, 0.3362]])
###########
tensor([[0.1445, 0.6191, 0.8177, 0.8839, 0.0373, 0.0040],
        [0.5070, 0.0301, 0.2572, 0.8463, 0.3284, 0.6825],
        [0.5919, 0.6822, 0.6130, 0.7989, 0.7659, 0.3362]])


#### Ans 8 : Both are not same

## Tensor Shapes
Reshaping a tensor is a frequently used operation. We can change the shape of a tensor without the memory copying overhead. There are two methods for that: `reshape` and `view`.

The difference is the following:

view tries to return a tensor, and it shares the same memory with the original tensor. In case, if it cannot reuse the same memory due to some reason, it just fails.
reshape always returns the tensor with the desired shape and tries to reuse the memory. If it cannot, it creates a copy
Let's see with the help of an example:

https://pytorch.org/docs/stable/tensors.html?highlight=view#torch.Tensor.view