<a href="https://colab.research.google.com/github/naveenkumark1/Extensive_Vision_and_AI_V.4/blob/master/Week3/pytorch101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
## Pytorch 101
# Pytorch is a machine leanring frame work that helps to build models for research prototyping and also for deployment

## Pytorch - Dataframes
#### In pytorch we have a data frame called Tensor - It is the generalisation of matrix and arrays to a higher dimension.

#### Tensor is an entity with defined order or rank 

#### Scalar - 0 order tensor
#### Vector - 1 order tensor 
#### Matrix - 2 order tensor
#### Array  - 3 order tensor


In [0]:
## Tensor Basics 
## Import Libraries 

import numpy as np
import torch

In [14]:
torch.zeros(0)  ## 0 order with zeros 

tensor([])

In [15]:
torch.zeros(1,2)  ## 1 Order 

tensor([[0., 0.]])

In [17]:
torch.zeros(2,2) ## 2 order 

tensor([[0., 0.],
        [0., 0.]])

In [18]:
# Random 3 order tensor

torch.rand(2,3,4)

tensor([[[0.6269, 0.7905, 0.2755, 0.7074],
         [0.7786, 0.3570, 0.0078, 0.6715],
         [0.5813, 0.6850, 0.8836, 0.4360]],

        [[0.5150, 0.1263, 0.8742, 0.6519],
         [0.8218, 0.3829, 0.1933, 0.2817],
         [0.1487, 0.2350, 0.9596, 0.6763]]])

In [19]:
torch.rand(3,2,3,2)

tensor([[[[0.7960, 0.3135],
          [0.7270, 0.5749],
          [0.0677, 0.9880]],

         [[0.2271, 0.2035],
          [0.4301, 0.4760],
          [0.4000, 0.6133]]],


        [[[0.2327, 0.4163],
          [0.2681, 0.9413],
          [0.3746, 0.0021]],

         [[0.1493, 0.5444],
          [0.4588, 0.0058],
          [0.7403, 0.2555]]],


        [[[0.8549, 0.2838],
          [0.3390, 0.8712],
          [0.3299, 0.6404]],

         [[0.5896, 0.5971],
          [0.2379, 0.7097],
          [0.7366, 0.5986]]]])

REF : https://pytorch.org/docs/stable/torch.html#creation-ops

##Question 1:
How many dimensions are there in a tensor defined as below?

In [12]:
torch.rand(1, 1, 1, 1)

tensor([[[[0.0428]]]])

### Ans 1 - 4 Dimension


In [9]:
torch.rand(2, 3, 4, 5)

tensor([[[[0.0020, 0.8128, 0.1107, 0.6865, 0.9165],
          [0.7100, 0.0781, 0.2275, 0.8027, 0.1700],
          [0.3811, 0.2469, 0.4164, 0.2039, 0.7449],
          [0.1164, 0.9278, 0.4014, 0.0741, 0.9596]],

         [[0.0112, 0.7129, 0.5908, 0.2394, 0.2850],
          [0.3561, 0.0771, 0.1490, 0.8068, 0.4286],
          [0.5982, 0.0571, 0.3978, 0.4299, 0.3059],
          [0.8803, 0.3565, 0.1660, 0.9566, 0.7013]],

         [[0.2024, 0.6090, 0.2072, 0.8754, 0.7012],
          [0.9112, 0.1733, 0.2836, 0.4149, 0.6158],
          [0.7070, 0.6148, 0.0578, 0.9896, 0.4964],
          [0.8069, 0.2671, 0.9520, 0.6188, 0.6889]]],


        [[[0.0309, 0.3159, 0.7605, 0.7584, 0.8534],
          [0.3667, 0.9347, 0.5098, 0.3710, 0.8075],
          [0.2753, 0.9575, 0.2628, 0.5204, 0.2444],
          [0.5769, 0.6812, 0.9647, 0.0382, 0.2802]],

         [[0.0064, 0.3266, 0.7432, 0.1329, 0.7845],
          [0.5373, 0.3635, 0.7268, 0.0023, 0.2325],
          [0.4969, 0.3641, 0.6534, 0.8909, 0.0301],
  

In [10]:
torch.rand(2, 3, 4, 5).size()

torch.Size([2, 3, 4, 5])

In [11]:
torch.rand(2, 3, 4, 5).shape

torch.Size([2, 3, 4, 5])